// GENERATED by scripts/gen-tokens.js from the design hand-off tokens.json.
// Do not edit by hand; change tokens.json and re-run the script.

export const tokens = {
	"font": {
		"heading": {
			"family": "Literata",
			"weights": [
				400,
				600
			],
			"italic": [
				400
			],
			"expoModule": "@expo-google-fonts/literata"
		},
		"body": {
			"family": "Manrope",
			"weights": [
				400,
				500,
				600,
				700
			],
			"expoModule": "@expo-google-fonts/manrope"
		},
		"size": {
			"xs": 12,
			"sm": 13,
			"md": 15,
			"lg": 17,
			"xl": 20,
			"2xl": 24,
			"3xl": 32,
			"4xl": 44,
			"5xl": 64
		},
		"lineHeight": {
			"tight": 1.15,
			"snug": 1.3,
			"normal": 1.5
		}
	},
	"space": {
		"1": 4,
		"2": 8,
		"3": 12,
		"4": 16,
		"5": 20,
		"6": 24,
		"8": 32,
		"10": 40,
		"12": 48,
		"16": 64
	},
	"radius": {
		"xs": 4,
		"sm": 8,
		"md": 12,
		"lg": 16,
		"xl": 24,
		"pill": 999
	},
	"shadow": {
		"sm": {
			"ios": {
				"shadowColor": "#1E2420",
				"shadowOpacity": 0.08,
				"shadowRadius": 2,
				"shadowOffset": {
					"width": 0,
					"height": 1
				}
			},
			"androidElevation": 1
		},
		"md": {
			"ios": {
				"shadowColor": "#1E2420",
				"shadowOpacity": 0.1,
				"shadowRadius": 12,
				"shadowOffset": {
					"width": 0,
					"height": 4
				}
			},
			"androidElevation": 3
		},
		"lg": {
			"ios": {
				"shadowColor": "#1E2420",
				"shadowOpacity": 0.16,
				"shadowRadius": 32,
				"shadowOffset": {
					"width": 0,
					"height": 12
				}
			},
			"androidElevation": 8
		}
	},
	"color": {
		"light": {
			"bg": "#F5F0E6",
			"surface": "#FFFDF8",
			"surface2": "#EDE6D8",
			"border": "#D9CFBC",
			"borderStrong": "#B9AD95",
			"ink": "#1E2420",
			"ink2": "#4A524C",
			"ink3": "#6F776F",
			"primary": "#2F5D46",
			"primaryHover": "#264C39",
			"onPrimary": "#F5F0E6",
			"primarySoft": "#DCE8E0",
			"accent": "#B5652B",
			"accentHover": "#9A5322",
			"onAccent": "#FFFDF8",
			"accentSoft": "#F3E1D2",
			"danger": "#A83C32",
			"dangerSoft": "#F3DBD8",
			"success": "#3E7B4F",
			"warning": "#B8862E",
			"info": "#3F6E7A",
			"focusRing": "#B5652B",
			"overlay": "rgba(30,36,32,0.45)"
		},
		"dark": {
			"bg": "#121714",
			"surface": "#1A211C",
			"surface2": "#232C26",
			"border": "#33403A",
			"borderStrong": "#4A5A51",
			"ink": "#EDE6D8",
			"ink2": "#B9B3A5",
			"ink3": "#858D84",
			"primary": "#5E9C78",
			"primaryHover": "#74B08D",
			"onPrimary": "#0F1712",
			"primarySoft": "#1F3529",
			"accent": "#D98A4E",
			"accentHover": "#E6A06C",
			"onAccent": "#1A120B",
			"accentSoft": "#3A2617",
			"danger": "#E07B71",
			"dangerSoft": "#3E2321",
			"success": "#6FB08A",
			"warning": "#D9A85A",
			"info": "#6FA3B0",
			"focusRing": "#D98A4E",
			"overlay": "rgba(0,0,0,0.6)"
		}
	},
	"node": {
		"male": {
			"light": {
				"fill": "#DCE9EC",
				"border": "#3F6E7A",
				"text": "#1E2420",
				"hoverFill": "#CFE1E5",
				"selectedBorder": "#B5652B"
			},
			"dark": {
				"fill": "#1F3A41",
				"border": "#6FA3B0",
				"text": "#EDE6D8",
				"hoverFill": "#25454D",
				"selectedBorder": "#D98A4E"
			}
		},
		"female": {
			"light": {
				"fill": "#F1DDD8",
				"border": "#A5584C",
				"text": "#1E2420",
				"hoverFill": "#EBD0CA",
				"selectedBorder": "#B5652B"
			},
			"dark": {
				"fill": "#43282A",
				"border": "#D08A80",
				"text": "#EDE6D8",
				"hoverFill": "#4E2F31",
				"selectedBorder": "#D98A4E"
			}
		},
		"borderWidth": 2,
		"selectedBorderWidth": 3,
		"radius": 10,
		"deceased": {
			"glyph": "†",
			"photoDesaturate": 0.6,
			"borderStyle": "solid"
		}
	},
	"relationship": {
		"BIOLOGICAL": {
			"light": "#2F5D46",
			"dark": "#6FB08A",
			"width": 2.5,
			"dashes": false,
			"glyph": "●",
			"label": "Biological",
			"arrowsWhenDirectional": true
		},
		"IN-LAW": {
			"light": "#B5652B",
			"dark": "#E09A5F",
			"width": 2,
			"dashes": [
				8,
				5
			],
			"glyph": "◆",
			"label": "In-law",
			"arrowsWhenDirectional": true,
			"note": "Group default. Marriage and cohabitation override via emphasis below."
		},
		"CHURCH": {
			"light": "#6B4E9B",
			"dark": "#A98BD6",
			"width": 2,
			"dashes": [
				2,
				5
			],
			"glyph": "✝",
			"label": "Church",
			"arrowsWhenDirectional": true
		},
		"IRRELEVANT": {
			"light": "#8A8F88",
			"dark": "#6F766F",
			"width": 1,
			"dashes": [
				3,
				7
			],
			"glyph": "○",
			"label": "Other",
			"arrowsWhenDirectional": true
		},
		"labelFont": {
			"face": "Manrope",
			"size": 11,
			"weight": 600,
			"lightColor": "#4A524C",
			"darkColor": "#B9B3A5"
		},
		"arrowScale": 0.7,
		"emphasis": {
			"strong": {
				"names": [
					"IS_MARRIED_TO"
				],
				"width": 4,
				"dashes": false,
				"labelWeight": 700,
				"description": "Heaviest line in the graph: solid, 4px, group color. A marriage reads as structure, like a beam."
			},
			"weak": {
				"names": [
					"LIVES_WITH",
					"IS_PARTNER_OF",
					"IS_ENGAGED_TO"
				],
				"width": 1.25,
				"dashes": [
					2,
					6
				],
				"labelWeight": 500,
				"description": "Lightest line: fine dots, 1.25px, group color at 100% (no alpha). Reads as provisional."
			}
		}
	},
	"canvas": {
		"light": {
			"bg": "#F5F0E6",
			"band": "#EDE6D8",
			"bandLabel": "#6F776F",
			"grid": "rgba(30,36,32,0.06)"
		},
		"dark": {
			"bg": "#121714",
			"band": "#1A211C",
			"bandLabel": "#858D84",
			"grid": "rgba(237,230,216,0.06)"
		},
		"bandYears": 20,
		"levelPx": 8,
		"columnPx": 200
	},
	"mobile": {
		"tabBarHeight": 56,
		"minTouch": 44,
		"sheetSnapPoints": {
			"person": [
				"38%",
				"92%"
			],
			"filters": [
				"55%",
				"92%"
			],
			"addPerson": [
				"92%"
			]
		},
		"zoomLOD": {
			"dot": {
				"max": 0.45
			},
			"compact": {
				"min": 0.45,
				"max": 0.9
			},
			"full": {
				"min": 0.9
			}
		},
		"motion": {
			"fast": 150,
			"base": 220,
			"slow": 320,
			"focus": 420,
			"easing": "cubic-bezier(0.2,0.8,0.2,1)"
		}
	},
	"brand": {
		"logoBottomNode": "#B5652B",
		"logoBottomNodeOnGreen": "#E0955E",
		"appIconBackground": "#2F5D46",
		"splashBackground": "#2F5D46",
		"scheme": "familytree://"
	},
	"extra": {
		"light": {
			"skeleton": "#E4DCCB",
			"focusGlow": "rgba(181,101,43,0.18)",
			"placeholder": "#8A8F88"
		},
		"dark": {
			"skeleton": "#2A342E",
			"focusGlow": "rgba(217,138,78,0.22)",
			"placeholder": "#6F766F"
		}
	}
} as const;

export type Tokens = typeof tokens;
