#!/usr/bin/env node
// Regenerates src/theme/tokens.ts from the design hand-off tokens.json.
// tokens.json is the single source of values; never edit tokens.ts by hand.
//   node scripts/gen-tokens.js [path/to/tokens.json]
const fs = require("fs");
const path = require("path");

const src =
	process.argv[2] ??
	path.join(__dirname, "../../docs/design/handoff/family-tree-visual-identity/project/tokens.json");
const t = JSON.parse(fs.readFileSync(src, "utf8"));

const out = {
	font: t.font,
	space: t.space,
	radius: t.radius,
	shadow: Object.fromEntries(
		Object.entries(t.shadow).map(([k, v]) => [k, { ios: v.ios, androidElevation: v.androidElevation }]),
	),
	color: t.color,
	node: {
		male: { light: t.node.male.light, dark: t.node.male.dark },
		female: { light: t.node.female.light, dark: t.node.female.dark },
		borderWidth: t.node.borderWidth,
		selectedBorderWidth: t.node.selectedBorderWidth,
		radius: t.node.radius,
		deceased: t.node.deceased,
	},
	relationship: {
		BIOLOGICAL: t.relationship.BIOLOGICAL,
		"IN-LAW": t.relationship["IN-LAW"],
		CHURCH: t.relationship.CHURCH,
		IRRELEVANT: t.relationship.IRRELEVANT,
		labelFont: t.relationship.labelFont,
		arrowScale: t.relationship.arrowScale,
		emphasis: {
			strong: t.relationship.emphasis.strong,
			weak: t.relationship.emphasis.weak,
		},
	},
	canvas: t.canvas,
	mobile: t.mobile,
	brand: t.brand,
	// Values used by Mobile.dc.html that tokens.json does not carry.
	extra: {
		light: { skeleton: "#E4DCCB", focusGlow: "rgba(181,101,43,0.18)", placeholder: "#8A8F88" },
		dark: { skeleton: "#2A342E", focusGlow: "rgba(217,138,78,0.22)", placeholder: "#6F766F" },
	},
};

const body =
	"// GENERATED by scripts/gen-tokens.js from the design hand-off tokens.json.\n" +
	"// Do not edit by hand; change tokens.json and re-run the script.\n\n" +
	`export const tokens = ${JSON.stringify(out, null, "\t")} as const;\n\n` +
	"export type Tokens = typeof tokens;\n";
fs.writeFileSync(path.join(__dirname, "../src/theme/tokens.ts"), body);
console.log("wrote src/theme/tokens.ts");
