name: Deploy Next.js site
on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "nextdeploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        working-directory: ./
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23.6.0"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: |
            ${{ github.workspace }}/yarn.lock
      - name: Install dependencies
        working-directory: ./
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Build with Next.js
        working-directory: ./
        run: ${{ steps.detect-package-manager.outputs.runner }} build
      - name: Add static JS scripts etc to the standalone app. In future consider uploading the static files to a CDN.
        working-directory: ./
        run: ${{ steps.detect-package-manager.outputs.runner }} add-static

      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ./.next/standalone
          target: ${{ vars.SSH_DIST_DEST }}

  # Deployment job
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Restart app
        run: |
          PB_API_LOGIN="${{ secrets.PB_API_LOGIN }}" PB_API_PASSWORD="${{ secrets.PB_API_PASSWORD }}" PB_URL="${{ secrets.PB_URL }}" SSR_POCKETBASE_URL="${{ secrets.SSR_POCKETBASE_URL }}" PORT="${{ vars.PORT }}" pm2 restart "Family Tree" --update-env && pm2 reset "Family Tree"
